CREATE OR REPLACE TRIGGER sourcedb.ARTICLETABLE_TRG 
BEFORE INSERT ON sourcedb.ARTICLETABLE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING THEN
      SELECT ARTICLETABLESEQUENCE.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/